apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: microservices-demo
build:
  artifacts:
    - image: bff
      context: app
      docker:
        dockerfile: app/apps/bff/Dockerfile
deploy:
  helm:
    releases:
    - name: manhcao-app
      chartPath: helm-charts
      valuesFiles:
      - helm-charts/values-local.yaml
      setValueTemplates:
        image.repository: "{{.IMAGE_MY_APP_IMAGE}}"
        image.tag: "{{.DIGEST_MY_APP_IMAGE}}"
portForward:
- resourceType: service
  resourceName: ingress-nginx-controller
  namespace: ingress-nginx
  port: 80
  localPort: 4505