env: prod

bff:
  name: bff
  image: gcr.io/nodal-cogency-446014-j2/bff
  port: 3000
  tag: "41c5b43"
  url: "https://manhcd.site/bff"

socketer:
  name: socketer
  image: gcr.io/nodal-cogency-446014-j2/socketer
  socketIoPort: 3001
  httpPort: 3002
  tag: "41c5b43" 

postgres:
  host: "postgres.manhcd.site"
  port: 5432
  user: admin
  password: admin 
  database: microservice-demo

auth:
  jwt_secret: "secret"
  password_secret_key: "secret"

externalIngress:
  host: "manhcd.site"
  name: "external-ingress"
  ingressClassName: nginx-external

argocdIngress:
  host: argocd.manhcd.site
  name: argocd-ingress
  namespace: argocd
  ingressClassName: nginx-argocd

redis:
  host: redis.manhcd.site
  port: 6379
  password: f55ce96b-6b46-465a-b1b9-7090fa8c7118
  db: 0