bff:
  name: bff
  image: gcr.io/nodal-cogency-446014-j2/bff
  port: 3000
  tag: 979b42a

postgres:
  host: 10.231.0.3
  port: 5432
  user: admin
  password: admin 
  database: microservice-demo

auth:
  jwt_secret: "secret"
  password_secret_key: "secret"