bff:
  name: bff
  image: gcr.io/nodal-cogency-446014-j2/bff
  port: 3000
  tag: "c9a0f1a"
  url: "https://manhcd.site/bff"

postgres:
  host: "postgres.manhcd.site"
  port: 5432
  user: admin
  password: admin 
  database: microservice-demo

auth:
  jwt_secret: "secret"
  password_secret_key: "secret"

externalIngress:
  name: "external-ingress"
  ingressClassName: nginx-external

argocdIngress:
  name: argocd-ingress
  namespace: argocd
  ingressClassName: nginx-argocd