bff:
  name: bff
  image: gcr.io/nodal-cogency-446014-j2/bff
  port: 3000
  tag: "f17c321"

postgres:
  host: 10.23.0.3
  port: 5432
  user: admin
  password: admin 
  database: microservice-demo

auth:
  jwt_secret: "secret"
  password_secret_key: "secret"

externalIngress:
  name: "external-ingress"
  ingressClassName: nginx-external

argocdIngress:
  name: argocd-ingress
  namespace: argocd
  ingressClassName: nginx-argocd