env: local

bff:
  name: bff
  image: bff 
  port: 3000
  tag: latest
  url: "http://localhost:3000/bff"

postgres:
  host: host.docker.internal
  port: 5432
  user: postgres
  password: postgres
  database: microservice-demo

auth:
  jwt_secret: "secret"
  password_secret_key: "secret"

externalIngress:
  host: localhost
  name: external-ingress
  ingressClassName: nginx

argocdIngress:
  host: localhost
  name: argocd-ingress
  namespace: default
  ingressClassName: nginx

redis:
  host: host.docker.internal
  port: 6390
  password: redis
  database: 0