env: prod

bff:
  name: bff
  image: gcr.io/nodal-cogency-446014-j2/bff
  port: 3000
  tag: "c5e0aee"
  url: "https://manhcd.site/bff"

socketer:
  name: socketer
  image: gcr.io/nodal-cogency-446014-j2/socketer
  socketIoPort: 3001
  httpPort: 3002
  tag: "c5e0aee" 

user:
  name: user
  image: gcr.io/nodal-cogency-446014-j2/user
  port: 50051
  tag: "d324a7e"
  url: "user:50051"

postgres:
  host: "postgres.manhcd.site"
  port: 5432
  user: admin
  password: admin 
  database: microservice-demo

auth:
  jwt_secret: "secret"
  password_secret_key: "secret"

externalIngress:
  host: "manhcd.site"
  name: "external-ingress"
  ingressClassName: nginx-external

argocdIngress:
  host: argocd.manhcd.site
  name: argocd-ingress
  namespace: argocd
  ingressClassName: nginx-argocd

redis:
  host: redis.manhcd.site
  port: 6379
  password: eb84b76a-41f8-4873-b532-5bbf36cedbfd
  db: 0