networks:
  microservices-demo-network:
    name: microservices-demo-network
    driver: bridge

services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: microservice-demo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservices-demo-network

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - '6390:6379'
    volumes:
      - redis_data:/data
    restart: always
    command: redis-server --requirepass "redis"
    networks:
      - microservices-demo-network

volumes:
  postgres_data:
  redis_data:
