steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/bff:$SHORT_SHA', '-f', 'apps/bff/Dockerfile', 'apps/bff']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/bff:$SHORT_SHA']
options:
  logging: CLOUD_LOGGING_ONLY