steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/socketer:$SHORT_SHA', '-f', 'app/apps/socketer/Dockerfile', 'app']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/socketer:$SHORT_SHA']
options:
  logging: CLOUD_LOGGING_ONLY