apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ required "argocdIngress.name is required" .Values.argocdIngress.name | quote }}
  namespace: {{ required "argocdIngress.namespace is required" .Values.argocdIngress.namespace | quote }}
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: {{ required "argocdIngress.ingressClassName is required" .Values.argocdIngress.ingressClassName | quote }}
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix 
            backend:
              service:
                name: argocd-server
                port:
                  number: 443
      {{- if .Values.argocdIngress.host }}
      host: {{ .Values.argocdIngress.host | quote }}
      {{- end }}