# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.socketer.name }}
  labels:
    app: {{ .Values.socketer.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.socketer.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.socketer.name }}
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: {{ .Values.socketer.image }}:{{ .Values.socketer.tag }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.socketer.httpPort }}
        - containerPort: {{ .Values.socketer.socketIoPort }}
        env:
        - name: SOCKETER_SERVICE_PORT
          value: {{ required "socketer.socketIoPort is required" .Values.socketer.socketIoPort | quote }}
        - name: SOCKETER_HTTP_PORT
          value: {{ required "socketer.httpPort is required" .Values.socketer.httpPort | quote }}
        - name: ENV
          value: {{ .Values.env | quote }}
        - name: REDIS_HOST
          value: {{ required "redis.host is required" .Values.redis.host | quote }}
        - name: REDIS_PORT
          value: {{ required "redis.port is required" .Values.redis.port | quote }}
        - name: REDIS_PASSWORD
          value: {{ required "redis.password is required" .Values.redis.password | quote }}
        - name: REDIS_DB
          value: {{ required "redis.db is required" .Values.redis.db | quote }}
        resources:
          requests:
            cpu: 200m
            memory: 180Mi
          limits:
            cpu: 300m
            memory: 300Mi

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.socketer.name }}
  labels:
    app: {{ .Values.socketer.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.socketer.name }}
  ports:
  - name: http 
    port: {{ .Values.socketer.httpPort }}
    targetPort: {{ .Values.socketer.httpPort }}
  - name: socketio
    port: {{ .Values.socketer.socketIoPort }}
    targetPort: {{ .Values.socketer.socketIoPort }}
